services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    command: sh -c "/app/entrypoint.sh && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - app
    restart: always

  celery-beat:
    build:
      context: .
    command: celery -A core beat -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - app
    restart: always

volumes:
  pgdata:
