# Generated by Django 5.1.7 on 2025-03-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "country"], name="weather_cit_name_09869a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("feels_like", models.FloatField()),
                ("humidity", models.PositiveSmallIntegerField()),
                ("pressure", models.PositiveSmallIntegerField()),
                ("wind_speed", models.FloatField()),
                ("wind_direction", models.PositiveSmallIntegerField()),
                ("weather_condition", models.CharField(db_index=True, max_length=255)),
                ("weather_description", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="weather.city",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(
                        fields=["city", "timestamp"],
                        name="weather_wea_city_id_23579d_idx",
                    )
                ],
            },
        ),
    ]
