# Generated by Django 5.1.7 on 2025-03-13 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="pressure",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MaxValueValidator(1200),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="wind_direction",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(360),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
